apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    management.listener.port = 15672
    loopback_users.guest = false
    clustering.use_longnames = true
