apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-probes
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq
      livenessProbe:
        httpGet:
          path: /api/health
          port: 15672
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /api/health
          port: 15672
        initialDelaySeconds: 15
        periodSeconds: 5
