apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | admin }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | admin }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.erlangCookie | b64enc }}
